### PR TITLE
Use error_logger instead of io:fwrite

### PR DESCRIPTION
**Pull request by surik**
Because we can redirect error_logger to something else

### CODE REVIEW

**Comment by uwiger** [comment]
+1, but could you please remove the tabs that snuck in? (note the indent-tabs-mode: nil in the header).

**Comment by surik** [comment]
Which the tabs do you mean?

**Comment by uwiger** [comment]
The diff shows that tabs have been inserted on lines 720, 856, 857, 1013 and 1063.

**Comment by uwiger** [comment]
...or maybe I read it wrong? :)

**Comment by uwiger** [comment]
Never mind. Thanks. Merged.

**Pull request merged**
